# Generated by Django 3.1 on 2020-11-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootleg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangologentry',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='loggedexception',
            managers=[
            ],
        ),
    ]
