# Generated by Django 3.1 on 2020-12-11 15:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bootleg', '0003_javascripterror_handled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='class',
            managers=[
                ('dql_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='loglevel',
            managers=[
                ('dql_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
