# Generated by Django 3.1.4 on 2021-01-01 04:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bootleg', '0005_auto_20201213_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=254, unique=True)),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Key value',
                'verbose_name_plural': 'Key values',
            },
            managers=[
                ('dql_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
