# Generated by Django 3.1.4 on 2021-01-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootleg', '0006_keyvalue'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='keyvalue',
            managers=[
            ],
        ),
    ]
