# Generated by Django 3.1.4 on 2021-01-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootleg', '0007_auto_20210101_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loglevel',
            options={},
        ),
    ]
